// 200+ unique driving tips for CrashCue daily tip feature
export const DRIVING_TIPS: string[] = [
    "Check blind spots on narrow roads to protect pedestrians and cyclists.",
    "Increase following distance during rainy weather to maintain safe driving habits.",
    "Stay alert near pedestrian crossings to maintain steady vehicle balance.",
    "Anticipate other drivers when entering roundabouts to improve reaction time.",
    "Drive smoothly on curved roads to avoid unexpected hazards.",
    "Watch vehicles behind you during foggy conditions to stay prepared for sudden stops.",
    "Stay in your lane in heavy traffic to maintain safe driving habits.",
    "Reduce speed during foggy conditions to improve road safety.",
    "Maintain steady speed on slippery roads to maintain steady vehicle balance.",
    "Increase following distance during windy weather to keep traffic flowing smoothly.",
    "Scan the road ahead when driving downhill to prevent sudden accidents.",
    "Keep your headlights on while driving in residential areas to prevent sudden accidents.",
    "Check blind spots during long trips to handle traffic safely.",
    "Avoid sudden steering when passing parked cars to stay prepared for sudden stops.",
    "Reduce speed near bus stops to reduce the risk of collisions.",
    "Keep both hands on the wheel when merging into traffic to maintain better control.",
    "Watch the roadside when driving uphill to maintain steady vehicle balance.",
    "Stay alert in school zones to improve road safety.",
    "Maintain tire grip near pedestrian crossings to maintain steady vehicle balance.",
    "Stay centered in your lane in city traffic to prevent sudden accidents.",
    "Avoid sudden steering during foggy conditions to avoid unexpected hazards.",
    "Stay aware of road signs during foggy conditions to reduce driver stress.",
    "Look for cyclists when driving uphill to avoid unexpected hazards.",
    "Maintain tire grip on unfamiliar roads to stay prepared for sudden stops.",
    "Watch vehicles behind you in city traffic to handle traffic safely.",
    "Slow down when merging into traffic to maintain better control of the vehicle.",
    "Watch vehicles behind you near pedestrian crossings to maintain safe driving habits.",
    "Anticipate other drivers near pedestrian crossings to keep traffic flowing smoothly.",
    "Stay centered in your lane on slippery roads to reduce driver stress.",
    "Observe traffic signals during rainy weather to reduce driver stress.",
    "Use gentle braking while overtaking another vehicle to reduce driver stress.",
    "Stay alert during rainy weather to improve reaction time.",
    "Reduce speed at night to maintain steady vehicle balance.",
    "Keep your headlights on in city traffic to maintain safe driving habits.",
    "Keep both hands on the wheel in school zones to stay prepared for sudden stops.",
    "Maintain steady speed when entering roundabouts to maintain steady vehicle balance.",
    "Watch vehicles behind you near railway crossings to improve road safety.",
    "Keep a safe gap when approaching traffic lights to improve road safety.",
    "Look far ahead when driving uphill to protect pedestrians and cyclists.",
    "Avoid sudden steering near bus stops to avoid sharp braking.",
    "Stay in your lane on slippery roads to avoid unexpected hazards.",
    "Watch for pedestrians on unfamiliar roads to improve road safety.",
    "Stay aware of road signs during long trips to protect pedestrians and cyclists.",
    "Stay aware of road signs near construction zones to reduce the risk of collisions.",
    "Keep a safe gap on unfamiliar roads to improve reaction time.",
    "Maintain steady speed near railway crossings to reduce the risk of collisions.",
    "Stay centered in your lane when entering roundabouts to reduce the risk of collisions.",
    "Stay alert at night to maintain safe driving habits.",
    "Slow down during rainy weather to improve reaction time.",
    "Look far ahead when driving downhill to maintain steady vehicle balance.",
    "Look far ahead in city traffic to ensure smoother driving.",
    "Reduce speed during long trips to maintain safe driving habits.",
    "Prepare to brake when entering roundabouts to improve road safety.",
    "Watch the roadside on slippery roads to ensure smoother driving.",
    "Keep a safe gap during long trips to improve reaction time.",
    "Look far ahead near pedestrian crossings to avoid unexpected hazards.",
    "Control acceleration near pedestrian crossings to maintain better control of the vehicle.",
    "Be patient in traffic when driving uphill to improve reaction time.",
    "Avoid sudden steering when traffic suddenly slows to keep traffic flowing smoothly.",
    "Increase following distance when merging into traffic to prevent sudden accidents.",
    "Look for cyclists while driving in residential areas to avoid sharp braking.",
    "Keep a safe gap at night to avoid unexpected hazards.",
    "Stay focused on the road when approaching intersections to prevent sudden accidents.",
    "Check blind spots while driving in residential areas to improve reaction time.",
    "Increase following distance in city traffic to maintain safe driving habits.",
    "Scan the road ahead on slippery roads to reduce the risk of collisions.",
    "Be patient in traffic at night to reduce the risk of collisions.",
    "Avoid sudden steering while entering parking lots to reduce the risk of collisions.",
    "Maintain steady speed near bus stops to maintain steady vehicle balance.",
    "Use gentle braking on slippery roads to stay prepared for sudden stops.",
    "Observe traffic signals when passing parked cars to protect pedestrians and cyclists.",
    "Maintain tire grip in heavy traffic to maintain safe driving habits.",
    "Keep both hands on the wheel near railway crossings to reduce driver stress.",
    "Keep your headlights on in crowded streets to prevent sudden accidents.",
    "Stay aware of road signs on unfamiliar roads to protect pedestrians and cyclists.",
    "Maintain tire grip near construction zones to keep traffic flowing smoothly.",
    "Look for cyclists near pedestrian crossings to avoid unexpected hazards.",
    "Scan the road ahead near railway crossings to improve road safety.",
    "Check blind spots in school zones to avoid unexpected hazards.",
    "Increase following distance while overtaking another vehicle to improve road safety.",
    "Use gentle braking when driving downhill to reduce driver stress.",
    "Stay focused on the road while overtaking another vehicle to reduce the risk of collisions.",
    "Prepare to brake on highways to improve road safety.",
    "Stay aware of road signs during windy weather to improve road safety.",
    "Scan the road ahead while entering parking lots to avoid sharp braking.",
    "Stay alert while driving in residential areas to maintain better control of the vehicle.",
    "Check your mirrors in city traffic to reduce the risk of collisions.",
    "Scan the road ahead when passing parked cars to improve reaction time.",
    "Watch for pedestrians at night to keep traffic flowing smoothly.",
    "Prepare to brake while driving in residential areas to maintain steady vehicle balance.",
    "Stay aware of road signs while entering parking lots to maintain better control.",
    "Maintain steady speed near pedestrian crossings to maintain safe driving habits.",
    "Reduce speed on narrow roads to prevent sudden accidents.",
    "Stay in your lane when approaching intersections to avoid unexpected hazards.",
    "Avoid sudden steering at night to avoid sharp braking.",
    "Slow down near railway crossings to improve road safety.",
    "Watch vehicles behind you during foggy conditions to reduce the risk of collisions.",
    "Anticipate other drivers while driving in residential areas to keep traffic flowing smoothly.",
    "Stay in your lane when driving uphill to maintain steady vehicle balance.",
    "Scan the road ahead on unfamiliar roads to handle traffic safely.",
    "Use gentle braking while entering parking lots to reduce driver stress.",
    "Slow down when traffic suddenly slows to maintain steady vehicle balance.",
    "Keep your headlights on on curved roads to improve road safety.",
    "Look for cyclists near bus stops to prevent sudden accidents.",
    "Control acceleration on unfamiliar roads to maintain safe driving habits.",
    "Check blind spots in city traffic to protect pedestrians and cyclists.",
    "Check your mirrors when passing parked cars to handle traffic safely.",
    "Control acceleration when approaching intersections to handle traffic safely.",
    "Slow down at night to protect pedestrians and cyclists.",
    "Increase following distance during foggy conditions to improve road safety.",
    "Scan the road ahead when parking to keep traffic flowing smoothly.",
    "Control acceleration near railway crossings to handle traffic safely.",
    "Observe traffic signals while entering parking lots to stay prepared for sudden stops.",
    "Keep a safe gap when merging into traffic to maintain safe driving habits.",
    "Prepare to brake during foggy conditions to improve reaction time.",
    "Control acceleration when driving downhill to avoid unexpected hazards.",
    "Scan the road ahead at night to prevent sudden accidents.",
    "Use gentle braking on unfamiliar roads to protect pedestrians and cyclists.",
    "Check blind spots in school zones to maintain safe driving habits.",
    "Use gentle braking in school zones to reduce driver stress.",
    "Stay centered in your lane on unfamiliar roads to stay prepared for sudden stops.",
    "Scan the road ahead when merging into traffic to maintain safe driving habits.",
    "Stay focused on the road on highways to prevent sudden accidents.",
    "Watch for pedestrians near bus stops to prevent sudden accidents.",
    "Maintain tire grip during long trips to improve road safety.",
    "Stay focused on the road while entering parking lots to protect pedestrians and cyclists.",
    "Reduce speed near railway crossings to reduce driver stress.",
    "Keep both hands on the wheel when driving downhill to handle traffic safely.",
    "Be patient in traffic while overtaking another vehicle to avoid unexpected hazards.",
    "Check blind spots when parking to improve reaction time.",
    "Increase following distance when traffic suddenly slows to improve reaction time.",
    "Observe traffic signals on curved roads to reduce driver stress.",
    "Control acceleration near railway crossings to keep traffic flowing smoothly.",
    "Observe traffic signals at night to improve road safety.",
    "Increase following distance on curved roads to improve road safety.",
    "Watch for pedestrians near bus stops to maintain better control of the vehicle.",
    "Maintain tire grip when traffic suddenly slows to improve reaction time.",
    "Be patient in traffic near pedestrian crossings to prevent sudden accidents.",
    "Look far ahead while driving in residential areas to maintain safe driving habits.",
    "Scan the road ahead when approaching traffic lights to stay prepared for sudden stops.",
    "Watch for pedestrians in school zones to prevent sudden accidents.",
    "Observe traffic signals in crowded streets to ensure smoother driving.",
    "Look for cyclists during windy weather to reduce the risk of collisions.",
    "Be patient in traffic on highways to prevent sudden accidents.",
    "Look for cyclists in city traffic to reduce the risk of collisions.",
    "Use gentle braking on curved roads to improve reaction time.",
    "Keep both hands on the wheel near pedestrian crossings to ensure smoother driving.",
    "Stay in your lane during foggy conditions to protect pedestrians and cyclists.",
    "Keep both hands on the wheel when merging into traffic to reduce the risk of collisions.",
    "Keep a safe gap on narrow roads to ensure smoother driving.",
    "Increase following distance while driving in residential areas to improve road safety.",
    "Keep your headlights on when driving uphill to reduce driver stress.",
    "Stay centered in your lane in school zones to improve reaction time.",
    "Maintain steady speed near pedestrian crossings to improve reaction time.",
    "Prepare to brake in school zones to avoid unexpected hazards.",
    "Use gentle braking on unfamiliar roads to maintain safe driving habits.",
    "Monitor your dashboard during foggy conditions to keep traffic flowing smoothly.",
    "Maintain steady speed during foggy conditions to avoid unexpected hazards.",
    "Stay in your lane on unfamiliar roads to improve reaction time.",
    "Prepare to brake in school zones to improve road safety.",
    "Anticipate other drivers near construction zones to ensure smoother driving.",
    "Reduce speed when driving uphill to improve reaction time.",
    "Stay aware of road signs near pedestrian crossings to improve reaction time.",
    "Anticipate other drivers in school zones to protect pedestrians and cyclists.",
    "Look far ahead during long trips to reduce driver stress.",
    "Watch the roadside while driving in residential areas to avoid sharp braking.",
    "Prepare to brake on highways to handle traffic safely.",
    "Monitor your dashboard near railway crossings to improve reaction time.",
    "Control acceleration on curved roads to improve road safety.",
    "Prepare to brake near bus stops to handle traffic safely.",
    "Look for cyclists near railway crossings to maintain steady vehicle balance.",
    "Keep your headlights on at night to avoid sharp braking.",
    "Avoid sudden steering when parking to reduce the risk of collisions.",
    "Watch vehicles behind you when merging into traffic to maintain steady vehicle balance.",
    "Maintain tire grip when merging into traffic to keep traffic flowing smoothly.",
    "Avoid sudden steering during foggy conditions to reduce the risk of collisions.",
    "Watch for pedestrians during foggy conditions to reduce driver stress.",
    "Anticipate other drivers when passing parked cars to improve reaction time.",
    "Stay focused on the road on curved roads to prevent sudden accidents.",
    "Look for cyclists when entering roundabouts to maintain steady vehicle balance.",
    "Stay alert near construction zones to stay prepared for sudden stops.",
    "Drive smoothly when driving downhill to maintain safe driving habits.",
    "Maintain tire grip in crowded streets to maintain safe driving habits.",
    "Watch vehicles behind you on narrow roads to reduce driver stress.",
    "Increase following distance when driving downhill to avoid unexpected hazards.",
    "Stay focused on the road when driving uphill to avoid sharp braking.",
    "Slow down during foggy conditions to handle traffic safely.",
    "Use gentle braking at night to maintain steady vehicle balance.",
    "Avoid sudden steering during windy weather to protect pedestrians and cyclists.",
    "Keep both hands on the wheel in heavy traffic to reduce driver stress.",
    "Watch for pedestrians on narrow roads to reduce driver stress.",
    "Look for cyclists when driving downhill to improve reaction time.",
    "Scan the road ahead when approaching intersections to reduce driver stress.",
    "Use gentle braking when driving uphill to maintain better control of the vehicle.",
    "Keep your headlights on near pedestrian crossings to reduce the risk of collisions.",
    "Keep your headlights on when approaching intersections to improve reaction time.",
    "Look far ahead when parking to maintain safe driving habits.",
    "Maintain tire grip while overtaking another vehicle to reduce the risk of collisions.",
    "Maintain tire grip when merging into traffic to reduce the risk of collisions.",
    "Watch for pedestrians in heavy traffic to protect pedestrians and cyclists.",
    "Observe traffic signals when parking to maintain better control of the vehicle.",
    "Observe traffic signals during windy weather to avoid unexpected hazards.",
    "Stay aware of road signs while overtaking another vehicle to maintain steady vehicle balance.",
    "Use gentle braking while entering parking lots to avoid unexpected hazards.",
    "Be patient in traffic when driving downhill to protect pedestrians and cyclists.",
    "Stay in your lane when merging into traffic to improve road safety.",
    "Keep a safe gap when driving downhill to maintain better control of the vehicle.",
    "Watch for pedestrians in heavy traffic to maintain safe driving habits.",
    "Keep both hands on the wheel on narrow roads to reduce driver stress.",
    "Keep your headlights on on highways to prevent sudden accidents.",
    "Stay aware of road signs when passing parked cars to ensure smoother driving.",
    "Increase following distance in school zones to maintain steady vehicle balance.",
    "Control acceleration in heavy traffic to improve road safety.",
    "Keep your headlights on on unfamiliar roads to maintain steady vehicle balance.",
    "Reduce speed near pedestrian crossings to maintain better control of the vehicle.",
    "Look for cyclists on highways to reduce driver stress.",
    "Look far ahead on curved roads to ensure smoother driving.",
    "Anticipate other drivers near bus stops to avoid sharp braking.",
    "Control acceleration on narrow roads to stay prepared for sudden stops.",
    "Slow down in heavy traffic to handle traffic safely.",
    "Control acceleration while driving in residential areas to maintain safe driving habits.",
    "Stay aware of road signs during windy weather to maintain safe driving habits.",
    "Watch for pedestrians on curved roads to handle traffic safely.",
    "Keep a safe gap when approaching intersections to maintain better control of the vehicle.",
    "Prepare to brake during foggy conditions to protect pedestrians and cyclists.",
    "Observe traffic signals in crowded streets to ensure smoother driving.",
];

/**
 * Returns a random driving tip.
 * Use this each time the app opens or the home screen mounts.
 */
export function getRandomDrivingTip(): string {
    const index = Math.floor(Math.random() * DRIVING_TIPS.length);
    return DRIVING_TIPS[index];
}
